### ISSUE TITLE
Rewriting the URL before it's sent to a BE server possible?

### ISSUE THREAD

**Issue by spidgorny** [ironboy/react-amazing-proxy#2]
Documentation says:

> Make sure that the api server listens to routes that begin with /api/.

That's a bummer in my case. The BE is a third-party I have little control of.
How can I plug a rewrite function that would convert 

```http://localhost:3000/api/login``` to 

```http://localhost:3000/login``` on-the-fly?

**Comment by ironboy** [comment]
Take a look at the setting possible in the proxy-settings.js file.

Change the handleWithAPI method in this file so taht it does any pattern matching you want. As long as this method returns true the request will be sent to your backend.

Examle

```js
handleWithApi(url) {
  return url.indexOf('/login/') === 0;
}
```
